### ISSUE TITLE
_get_tally_cards method in MCNPinput.py to be improved

### ISSUE THREAD

**Issue by AlbertoBittes** [Fusion4Energy/F4Enix#48]
The _get_tally_cards method doesn't find 'sd' 'e' 'em', ... cards, which are tally related

**Comment by dodu94** [comment]
That is by design, they are considered part of the tally F<number> in order for them to stay all together. Add support for the individual cards that are part of the tally would be an additional step that is not foreseen for the moment. It may be on the table again if we switch to a more sofisticated parser (SLY) for the input files
